# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47bca201eff576e5fc21125b56420b5d4bdc35fe9f3f28f8e4c790cae2e194b747ec846f87cbaecb3f32b3b9d302484a49d388b4644a4b7155e7ad420bacd222

test:
  secret_key_base: 170710421e9b5644554fc7334059a4ae98ab72e6b5e2b89dab82f0a55780f8630a1c21dd1ecc9443bef143a0fd224934c091648a7c70fc4f07e9ce91273070f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
